-- OnlySubs: User Video States Table
-- Run this in Supabase Dashboard -> SQL Editor

-- 1. Create user_video_states table
CREATE TABLE IF NOT EXISTS user_video_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    video_id TEXT NOT NULL,
    has_new BOOLEAN DEFAULT true,
    read_at TIMESTAMPTZ,
    transcript_unlocked BOOLEAN DEFAULT false,
    transcript_unlocked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, video_id)
);

-- 2. Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_user_video_states_user_has_new
ON user_video_states(user_id, has_new) WHERE has_new = true;

-- 3. Grant permissions
GRANT ALL ON user_video_states TO authenticated;
GRANT ALL ON user_video_states TO anon;

-- 4. Enable RLS
ALTER TABLE user_video_states ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policy: users can only see their own states
-- Note: user_id is TEXT (not uuid) to match existing tables
CREATE POLICY "Users can view own states"
ON user_video_states FOR SELECT
USING (user_id = 'guest');

CREATE POLICY "Users can insert own states"
ON user_video_states FOR INSERT
WITH CHECK (user_id = 'guest');

CREATE POLICY "Users can update own states"
ON user_video_states FOR UPDATE
USING (user_id = 'guest');

-- Note: For authenticated users, the app will handle user_id check in application layer